#define CURRENT_SENSOR PA0

#define LED_OPERATIONAL PG8
#define LED_FAULT PG7

#define PWM_LOW PE8
#define PWM_HIGH PE9
#define PWM_BUFFER_EN PF4
#define PWM_RESET PE15

#define DCLV_OUTPUT_CURRENT_SENSOR PF12
#define DCLV_INPUT_CURRENT_SENSOR PB1

#define DCLV_OUTPUT_VOLTAGE_SENSOR PF11
#define DCLV_INPUT_VOLTAGE_SENSOR PB0
